- index.html
- js/main.js
- js/signup.js
- style.scss
- 아이디/비밀번호 자동완성에서 검색창을 id로 인식하는 오륩라생
- 로그인창을 form으로 감싸주어서 브라우저에서 인식할수있게 변경
- 로그인도 button submit으로 바꾸어 enter로도 가능하게 변경
- 라우팅 코드 변경(새로고침시에도 동작하게)
- 일부 주석 추가
> fix: Fix Html structure for id/pw autocomplete

- js/main.js
- js/signup.js
- 24시간 후 localStorage에서도 token값이 사라지도록 localStorage 만료 시간을 설정했습니다.
setItemWithExpireTime, getItemWithExpireTime 함수를 만들었음
- authlogin 오류가 나와서 localStorage에 토큰 값이 있을 때만 authLogin 함수가 실행하도록 고쳤습니다.
> feat: Create setItemWithExpireTime feature, authLogin feature

- js/main.js
- js/requests.js
- js/signup.js
- api 함수들을 requests.js로 모듈화 해줬습니다.
- API_KEY, USER_NAME 변수로 만들었습니다.
> feat: Create requests.js 

- index.html
- js/admin.js
- js/main.js
- js/requests.js
- reset.css
- style.scss
- 주소창에 `/#/admin` 을 붙여서 관리자페이지로 이동할수 있습니다
- 현재는 제품추가까지 가능
> feat: Create Admin page & CreateItem

- index.html
- js/admin.js
- js/main.js
- js/signup.js
- merge conflict 에러때 제대로 못보고 정상코드를 날려버렸네요.....
- 다 복구했고 + admin.js코드 약간 수정입니다
> fix: Fix merge conflict Error

- index.html
- js/main.js
- js/requests.js
- js/signup.js
- js 파일 리팩토링 : 함수 모듈화 했습니다.
- HTML user-info-pwd class를 id로 변경해줬습니다.
> refactor: Modulization function

- index.html
- js/admin.js
- js/main.js
- js/requests.js
- js/signup.js
- style.scss
- 관리자페이지에서 제품추가/ 제품확인/ 제품 삭제 가능합니다
- 관리자 계정으로만 접근가능하도록 해놨습니다
- 관리자 계정은 우리 노션에....
> feat: Create Admin page & Authorization

- index.html
- js/main.js
- js/requests.js
- style.scss
- 모달 창 만듦
- 유저 페이지에서 변경 눌렀을 때, 변경이 완료되면 모달 창 띄우게 만듦
> feat: Change Modal

- index.html
- js/admin.js
- js/main.js
- js/requests.js
- js/swiper.js
- style.scss
> feat: Create Admin add image

- index.html
- js/main.js
- js/swiper.js
- package-lock.json
- package.json
- style.scss
> feat: Create saleslist-container

- index.html
- js/admin.js
- js/main.js
- js/requests.js
- style.scss
> fix: Fix merge errors

- index.html
- js/main.js
- js/requests.js
- package-lock.json
- package.json
- style.scss
> feat : Create detail page

- index.html
- js/main.js
- js/requests.js
- js/signup.js
- style.scss
- 로그인 시 이메일 유효성 검사 코드 작성했습니다.
- 로그인 실패 시 나오는 모달창을 만들었습니다.
> feat: Create Login Validation funcntion

- index.html
- js/admin.js
- js/main.js
- js/render.js
- js/store.js
- style.scss
- 관리자 파일 모듈화
- 카테고리 라우터 생성
- 카테고리 렌더링 함수 작성
> feat: Create category rendering

- js/main.js
- js/render.js
- js/store.js
- 검색기능 구현(한글 디코딩까지)
- 예외처리 해야함
> feat: Create input search feature

- index.html
- js/main.js
- js/render.js
- js/requests.js
- js/store.js
- layout/category.scss
- layout/detail.scss
- layout/purchase.scss
- 상세 페이지 수정
- 구매 페이지 수정
- 초기화면 렌더링 수정
> feat: Modify purchase function

- js/main.js
- js/render.js
- js/store.js
- layout/cart.scss
> fix: renderCartPages Error

- index.html
- js/cart.js
- js/main.js
- js/render.js
- js/requests.js
- js/signup.js
- js/store.js
- layout/signup.scss
- When signup, if email overlap error-msg appear
- Change renderCartPages function position
> fix: signup-error-msg, Change renderCartPages function position

- index.html
- js/main.js
- js/recent.js
- js/render.js
- js/swiper.js
- 장바구니 전체 구매 기능 구현완료
- 스와이퍼 html에 넣어둔것 js innerHTML로 변경 완료.
> feat: Create Entire cart purchase feature

- js/render.js
- js/swiper.js
> fix: Fix account title not displaying

- js/main.js
- js/render.js
- js/requests.js
- 구매기능 완료입니다
- 구매완료, 실패시 모달창 띄워주기
- 모달 닫으면 홈으로 간다.
> feat: Create Purchase feature

- index.html
- layout/style.scss
> fix: Fix header css to responsive web

- index.html
- js/render.js
- layout/qna.scss
> feat: Modify qna page

- index.html
- js/main.js
- js/render.js
- layout/account.scss
- layout/cart.scss
- layout/qna.scss
- layout/style.scss
- 초기 렌더링시 display수정(cart, qna)
- 카테고리페이지 정렬기능 구현
- account 스타일 수정
> feat: Create Category page sorting feature

- index.html
- js/main.js
- js/render.js
- js/requests.js
- js/signup.js
- js/store.js
- layout/qna.scss
- layout/signup.scss
- 인증(로그인, 회원가입, 회원정보페이지) 관련 함수, api 수정
-  store.js 변수들 객체로 묶음
- 구매 완료한 것들 장바구니에서 제거되게함
> fix: Fix Certification related functions, Variables are enclosed in objects, feat: Remove purchased items from cart

- js/account.js
- js/cart.js
- js/main.js
- js/recent.js
- js/render.js
- js/requests.js
- js/signup.js
- js/store.js
- js/swiper.js
- 검색 기능 api로 교체
- 라우팅 코드 하나의 함수로 교체
- 자잘한 주석과 안쓰는 변수들 삭제
- 변수 store.js에서 객체화
- 주석들 추가
> refactor: Refactor search logic codes && change router code into function

- js/requests.js
> feat: Add try-catch statement on Request API

- js/signup.js
- 유효성검사 event를 focusin, focusout에서 input으로 변경함
> fix: Fix validation function

- layout/detail.scss
> feat: Change size for title on detail page

- js/main.js
> feat: Add welcome image on console

- js/account.js
- js/cart.js
- js/main.js
- js/recent.js
- js/render.js
- js/requests.js
- layout/account.scss
- layout/signup.scss
- 스와이퍼 함수화
- scss 중복되는것들 하나로 정리
- 변수들 정리
> refactor: Refactor codes
